server:
  port: 8008

spring:
  application:
    name: SPRINGCLOUD-PROVIDER-SEATA-STORAGE8008 #注意:服务名不要出现_
  devtools:
    restart:
      enabled: true
  logging: #Spring运行日志配置
    level: info
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.0.2:3306/seata_storage
    username: root
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging: #OpenFeign增强日志配置
  level:
    org.openatom.springcloud.services.PaymentServiceSentinelOpenFeign: debug  #OpenFeign日志以什么级别监控哪个接口
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.openatom.springcloud.entities    # 所有Entity别名类所在包

seata:
  enabled: true
  application-id: seata_strogre
  # 客户端和服务端在同一个事务组
  tx-service-group: my_test_tx_group
  # 事务群组,配置项值为TC集群名,需要与服务端保持一致
  service:
    vgroup-mapping:
      my_test_tx_group: default
#--------------------如果seata使用的nacos和当前项目使用的nacos是同一个,则不用配置下面代码:开始--------------------
  #整合nacos配置中心
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: SEATA_GROUP
      data-id: seataServer.properties
      username: nacos
      password: nacos
  #整合nacos注册中心
  registry:
    type: nacos
    nacos:
      application: seata-server # 服务名,与服务端中registry.conf配置要一致
      server-addr: localhost:8848
      group: SEATA_GROUP
      # 默认TC集群名
      cluster: default
      username: nacos
      password: nacos
#--------------------如果seata使用的nacos和当前项目使用的nacos是同一个,则不用配置下面代码:结束--------------------
