server:
  port: 80

spring:
    application:
        name: SPRINGCLOUD-CONSUMER-LOADBALANCE-RIBBON-HARDCODE-ORDER80 #注意:服务名不要出现_
    devtools:
      restart:
        enabled: true
    logging:
      level: info
    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848 #配置Nacos地址

#服务提供方信息
service:
  provider:
    name: SPRINGCLOUD-PROVIDER-PAYMENT-SERVICE-CLUSTER
    url: http://${service.provider.name} #服务提供方名称
